# To Read 
https://shapely.readthedocs.io/en/stable/manual.html <br/>
https://docs.qgis.org/2.18/en/docs/pyqgis_developer_cookbook/geometry.html <br/>
https://automating-gis-processes.github.io/2017/lessons/L1/Geometric-Objects.html <br/>
http://www.cs.umd.edu/~hjs/pubs/jacoxtods07.pdf <br/>
https://gis.stackexchange.com/questions/121499/spatial-join-versus-classical-join <br/>
https://pro.arcgis.com/de/pro-app/tool-reference/big-data-analytics/join-features.htm <br/>
https://www.twilio.com/blog/2017/08/geospatial-analysis-python-geojson-geopandas.html <br/>
https://pypi.org/project/geojson/ <br>
https://tools.ietf.org/html/rfc7946#section-3.1.3 <br/>
Qgis Visuelle Überschneidungen 
Konkrete Fragestellungen

In [67]:
import geopandas as gpd
import pandas as pd
import numpy as np
pd.options.display.max_columns = None
unfaelle = gpd.read_file('unfaelle_berlin.geojson')
verkehrsmengen = gpd.read_file('Verkehrsmengen.geojson') 
ampeln = gpd.read_file('Ampeln.geojson')
laerm = gpd.read_file('Laerm.geojson')
bodenrichtwerte = gpd.read_file('Bodenrichtwerte.geojson')
tempolimits = gpd.read_file('Tempolimits.geojson') 
merge3 = gpd.read_file('U_VM_A_L_BRW.geojson')


Unfallart (Feld "UART")
1 = Zusammenstoß mit anfahrendem/anhaltendem/ruhendem Fahrzeug
2 = Zusammenstoß mit vorausfahrendem/wartendem Fahrzeug
3 = Zusammenstoß mit seitlich in gleicher Richtung fahrendem Fahrzeug
4 = Zusammenstoß mit entgegenkommendem Fahrzeug
5 = Zusammenstoß mit einbiegendem / kreuzendem Fahrzeug
6 = Zusammenstoß zwischen Fahrzeug und Fußgänger
7 = Aufprall auf Fahrbahnhindernis
8 = Abkommen von Fahrbahn nach rechts
9 = Abkommen von Fahrbahn nach links
0 = Unfall anderer Art

Unfallkategorie (Feld "UKATEGORIE")
1 = Unfall mit Getöteten
2 = Unfall mit Schwerverletzten
3 = Unfall mit Leichtverletzten


Unfalltyp (Feld "UTYP" bzw. "UTYP1")
1 = Fahrunfall
2 = Abbiegeunfall
3 = Einbiegen / Kreuzen-Unfall
4 = Überschreitenunfall
5 = Unfall durch ruhenden Verkehr
6 = Unfall im Längsverkehr
7 = sonstiger Unfall

Lichtverhältnisse (Feld "LICHT"):
0 = Tageslicht
1 = Dämmerung
2 = Dunkelheit

Straßenzustand (Feld "STRZUSTAND"):
0 = trocken
1 = nass/feucht/schlüpfrig
2 = winterglatt

Wochentag 
1 = Sonntag
2 = Montag
3 = Dienstag
4 = Mittwoch
5 = Donnerstag
6 = Freitag
7 = Samstag


Die in den Rohdaten enthaltenen Spalten ULAND, UREGBEZ, UKREIS, UGEMEINDE bilden den Amtlichen Gemeindeschlüssel ab. Die Kodierung ist hier abrufbar:
https://www.destatis.de/DE/ZahlenFakten/LaenderRegionen/Regionales/Gemeindeverzeichnis/Administrativ/Archiv/GVAuszugQ/AuszugGV3QAktuell.html

Die Werte in den Feldern LINREFX und LINREFY bilden die Koordinate des auf dem Straßenabschnitt liegenden Unfallortes (UTM-Koordinate des Referenzsystems ETRS89, Zone 32N).

In [49]:
unfaelle = unfaelle.drop(["ULAND","UREGBEZ","UJAHR"], axis=1)
unfaelle["UWOCHENTAG"] = unfaelle["UWOCHENTAG"] - 1
unfaelle["UWOCHENTAG"] = unfaelle["UWOCHENTAG"].replace(0, 7)
#To Do für später decodieren von UKreis und UGemeinde
unfaelle.describe()

,OBJECTID,UKREIS,UGEMEINDE,UMONAT,USTUNDE,UWOCHENTAG,UKATEGORIE,UART,UTYP1,ULICHTVERH,IstRad,IstPKW,IstFuss,IstKrad,IstGkfz,IstSonstige,STRZUSTAND,LINREFX,LINREFY
count,13649.000000,13649.000000,13649.000000,13649.000000,13649.000000,13649.000000,13649.000000,13649.000000,13649.000000,13649.000000,13649.000000,13649.000000,13649.000000,13649.000000,13649.000000,13649.000000,13649.000000,13649.000000,1.364900e+04
mean,190757.504506,5.424793,5.424793,6.728405,13.473441,3.582680,2.834640,3.626713,3.887171,0.446699,0.380321,0.817056,0.151147,0.157814,0.032457,0.133050,0.195472,797784.714863,5.826565e+06
std,30324.889510,3.495025,3.495025,3.175898,4.773724,1.831544,0.379519,2.147327,1.895501,0.796455,0.485483,0.386635,0.358205,0.364580,0.177216,0.339641,0.408232,6614.330070,5.157698e+03
min,112695.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,778444.698700,5.809746e+06
25%,198395.000000,2.000000,2.000000,4.000000,10.000000,2.000000,3.000000,2.000000,2.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,793462.791500,5.823267e+06
50%,201810.000000,5.000000,5.000000,7.000000,14.000000,4.000000,3.000000,5.000000,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,797762.199400,5.826844e+06
75%,205222.000000,8.000000,8.000000,9.000000,17.000000,5.000000,3.000000,5.000000,6.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,801550.244200,5.829905e+06
max,208853.000000,12.000000,12.000000,12.000000,23.000000,7.000000,3.000000,9.000000,7.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,822060.509200,5.842633e+06

In [50]:

unfaelle.head()

,OBJECTID,UKREIS,UGEMEINDE,UMONAT,USTUNDE,UWOCHENTAG,UKATEGORIE,UART,UTYP1,ULICHTVERH,IstRad,IstPKW,IstFuss,IstKrad,IstGkfz,IstSonstige,STRZUSTAND,LINREFX,LINREFY,geometry
0,112705,12,12,1,11,1,3,2,6,0,0,1,0,0,0,0,0,790639.5854,5.835010e+06,MULTIPOINT (790639.585 5835009.589)
1,112837,12,12,1,21,6,3,0,1,2,0,0,0,1,0,0,1,794735.9234,5.833764e+06,MULTIPOINT (794735.923 5833763.947)
2,113020,12,12,1,7,5,3,0,7,1,0,0,0,1,0,0,1,790106.5030,5.836070e+06,MULTIPOINT (790106.503 5836069.675)
3,113205,12,12,1,7,2,3,6,2,1,0,1,1,0,0,0,2,792159.9652,5.838427e+06,MULTIPOINT (792159.965 5838427.271)
4,113456,12,12,1,12,3,3,2,6,0,0,1,0,0,0,1,1,791035.8465,5.841190e+06,MULTIPOINT (791035.846 5841190.008)

In [51]:
unfaelle.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 13649 entries, 0 to 13648
Data columns (total 20 columns):
OBJECTID       13649 non-null int64
UKREIS         13649 non-null int64
UGEMEINDE      13649 non-null int64
UMONAT         13649 non-null int64
USTUNDE        13649 non-null int64
UWOCHENTAG     13649 non-null int64
UKATEGORIE     13649 non-null int64
UART           13649 non-null int64
UTYP1          13649 non-null int64
ULICHTVERH     13649 non-null int64
IstRad         13649 non-null int64
IstPKW         13649 non-null int64
IstFuss        13649 non-null int64
IstKrad        13649 non-null int64
IstGkfz        13649 non-null int64
IstSonstige    13649 non-null int64
STRZUSTAND     13649 non-null int64
LINREFX        13649 non-null float64
LINREFY        13649 non-null float64
geometry       13649 non-null geometry
dtypes: float64(2), geometry(1), int64(17)
memory usage: 2.1 MB

Verkehrsmengen 2014 (Umweltatlas)

Dargestellt werden die Verkehrsmengen im übergeordneten Straßennetz des Landes Berlin, welches als Grundlage u.a. für die Zwecke der Lärmminderungs- und Luftreinhalteplanung dient.
Die wesentlichen Grundlagen für die hier dargestellten Verkehrsmengen als DTV bilden die Kfz- und Lkw-Daten aus der vorliegenden Verkehrsstärkenkarte 2014 DTVw (DTV werktags) der Senatsverwaltung für Umwelt, Verkehr und Klimaschutz.
Die durchschnittliche tägliche Verkehrsstärke (DTV) ist der Mittelwert über alle Tage des Jahres für die Zahl der einen Straßenquerschnitt in beiden Fahrtrichtungen täglich passierenden Kraftfahrzeuge einschließlich Lkw, Motorräder und Busse.
Angaben zur durchschnittlichen werktäglichen Verkehrsstärke (DTVw) finden Sie hier: https://www.berlin.de/senuvk/verkehr/lenkung/vlb/de/erhebungen.shtml.

Ausführliche Informationen finden Sie in den Begleittexten der im Umweltatlas Berlin veröffentlichten Karten zum Thema Verkehrsmengen 07.01 (Ausgabe 2017).

Internet: http://www.stadtentwicklung.berlin.de/umwelt/umweltatlas/din_701.htm.



Verkehrsmengen 2014 (Umweltatlas)

Anzahl der Kraftfahrzeuge je 24 Stunden 2014 im übergeordneten Straßennetz incl. Pkw, Lkw, Motorräder, Lieferwagen, Linien- und Reisebusse als durchschnittliche tägliche Verkehrsstärke (DTV)

Feldname	Beschreibung
LINK_ID	Schlüssel
METER	Länge des Abschnittes [m]
STRASSE	Name des Straßenabschnittes
DTV	Durchschnittliche tägliche Verkehrsstärke (DTV) Kfz
PKW	DTV Pkw
LKW	DTV Lkw > 3,5 t (ohne Busse)
LIEFERWAGEN	DTV Lieferwagen ≤ 3,5 t
LINIENBUSSE	DTV Linienbusse
REISEBUSSE	DTV Reisebusse
KRAD	DTV Motorräder
HERKUNFT	Quelle Kfz-Daten
Ausführliche Informationen finden Sie in den Begleittexten der im Umweltatlas Berlin veröffentlichten Karte 07.01.
Internet: http://www.stadtentwicklung.berlin.de/umwelt/umweltatlas/id701.htm

In [52]:
verkehrsmengen.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 10086 entries, 0 to 10085
Data columns (total 11 columns):
METER          10086 non-null float64
STR_NAME       10086 non-null object
DTV            10086 non-null float64
PKW            10086 non-null float64
LKW            10086 non-null float64
LIEFERWAGEN    10086 non-null float64
LINIENBUSSE    10086 non-null float64
REISEBUSSE     10086 non-null float64
KRAD           10086 non-null float64
HERKUNFT       10038 non-null object
geometry       10086 non-null geometry
dtypes: float64(8), geometry(1), object(2)
memory usage: 866.8+ KB

In [53]:

verkehrsmengen["ANTEIL_PKW"] = verkehrsmengen["PKW"]*100/verkehrsmengen["DTV"]
verkehrsmengen["ANTEIL_PKW"] = verkehrsmengen["ANTEIL_PKW"].fillna(0)
verkehrsmengen["ANTEIL_LKW"] = verkehrsmengen["LKW"]*100/verkehrsmengen["DTV"]
verkehrsmengen["ANTEIL_LKW"] = verkehrsmengen["ANTEIL_LKW"].fillna(0)
verkehrsmengen["ANTEIL_LIEFERWAGEN"] = verkehrsmengen["LIEFERWAGEN"]*100/verkehrsmengen["DTV"]
verkehrsmengen["ANTEIL_LIEFERWAGEN"] = verkehrsmengen["ANTEIL_LIEFERWAGEN"].fillna(0)
verkehrsmengen["ANTEIL_LINIENBUSSE"] = verkehrsmengen["LINIENBUSSE"]*100/verkehrsmengen["DTV"]
verkehrsmengen["ANTEIL_LINIENBUSSE"] = verkehrsmengen["ANTEIL_LINIENBUSSE"].fillna(0)
verkehrsmengen.loc[verkehrsmengen["ANTEIL_LINIENBUSSE"] == np.inf, ['DTV']] = verkehrsmengen.loc[verkehrsmengen["ANTEIL_LINIENBUSSE"] == np.inf, ['LINIENBUSSE']]
verkehrsmengen.loc[verkehrsmengen["ANTEIL_LINIENBUSSE"] == np.inf, ['ANTEIL_LINIENBUSSE']] = 100
verkehrsmengen["ANTEIL_REISEBUSSE"] = verkehrsmengen["REISEBUSSE"]*100/verkehrsmengen["DTV"]
verkehrsmengen["ANTEIL_REISEBUSSE"] = verkehrsmengen["ANTEIL_REISEBUSSE"].fillna(0)
verkehrsmengen["ANTEIL_KRAD"] = verkehrsmengen["KRAD"]*100/verkehrsmengen["DTV"]
verkehrsmengen["ANTEIL_KRAD"] = verkehrsmengen["ANTEIL_KRAD"].fillna(0)
verkehrsmengen = verkehrsmengen.drop(["METER","HERKUNFT","PKW","LKW","LIEFERWAGEN","LINIENBUSSE","REISEBUSSE","KRAD"], axis=1)
verkehrsmengen.head()

,METER,STR_NAME,DTV,PKW,LKW,LIEFERWAGEN,LINIENBUSSE,REISEBUSSE,KRAD,HERKUNFT,geometry,ANTEIL_PKW,ANTEIL_LKW,ANTEIL_LIEFERWAGEN,ANTEIL_LINIENBUSSE,ANTEIL_REISEBUSSE,ANTEIL_KRAD
0,71.0,Alt-Buch,12960.0,10572.0,618.0,1322.0,230.0,32.0,186.0,"Verkehrsstärkenkarte 2014, VLB","LINESTRING (398257.364 5832698.211, 398290.273...",81.574074,4.768519,10.200617,1.774691,0.246914,1.435185
1,119.0,Alt-Buch,12960.0,10592.0,618.0,1322.0,210.0,32.0,186.0,"Verkehrsstärkenkarte 2014, VLB","LINESTRING (398324.724 5832720.497, 398335.699...",81.728395,4.768519,10.200617,1.620370,0.246914,1.435185
2,296.0,Alt-Buch,12960.0,10602.0,618.0,1322.0,200.0,32.0,186.0,"Verkehrsstärkenkarte 2014, VLB","LINESTRING (398437.824 5832759.259, 398454.167...",81.805556,4.768519,10.200617,1.543210,0.246914,1.435185
3,236.0,Alte Kaulsdorfer Str.,7258.0,6078.0,131.0,741.0,150.0,2.0,156.0,"Modellrechnung 2014, VMZ","LINESTRING (403377.118 5813297.220, 403379.105...",83.742078,1.804905,10.209424,2.066685,0.027556,2.149352
4,165.0,Alte Schönhauser Str.,2764.0,2242.0,80.0,282.0,0.0,16.0,144.0,"Zähldaten VLB, 20140916","LINESTRING (391884.118 5820618.870, 391898.317...",81.114327,2.894356,10.202605,0.000000,0.578871,5.209841

In [56]:
verkehrsmengen.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 10086 entries, 0 to 10085
Data columns (total 17 columns):
METER                 10086 non-null float64
STR_NAME              10086 non-null object
DTV                   10082 non-null float64
PKW                   10086 non-null float64
LKW                   10086 non-null float64
LIEFERWAGEN           10086 non-null float64
LINIENBUSSE           10086 non-null float64
REISEBUSSE            10086 non-null float64
KRAD                  10086 non-null float64
HERKUNFT              10038 non-null object
geometry              10086 non-null geometry
ANTEIL_PKW            10086 non-null float64
ANTEIL_LKW            10086 non-null float64
ANTEIL_LIEFERWAGEN    10086 non-null float64
ANTEIL_LINIENBUSSE    10086 non-null float64
ANTEIL_REISEBUSSE     10086 non-null float64
ANTEIL_KRAD           10086 non-null float64
dtypes: float64(14), geometry(1), object(2)
memory usage: 1.3+ MB

Wie zu mergen? MULTIPOINT Auf Linestring --> Liegt der Punkt auf der Straße <br/> 
Welche Spots sind relativ zur Verkehrsmenge unsicher 
Gibt es Korrelationen zwischen einem erhöhten Anteil an bestimmten Fahrzeugtypen und gefährlichen Unfallstellen.

In [26]:
ampeln.head()

,NAME,KNAME,geometry
0,Müllerstr. / Schulzendorfer Str. - Sellerstr.,01001,POINT (389482.928 5822340.930)
1,Müllerstr. / Fennstr.,01002,POINT (389354.787 5822474.063)
2,Müllerstr. / Lindower Str. - Lynarstr.,01003,POINT (389202.940 5822641.359)
3,Müllerstr. / Gerichtstr. - Triftstr.,01004,POINT (388916.000 5822904.000)
4,Müllerstr. / Luxemburger Str. - Schulstr,01005,POINT (388733.356 5823078.790)

Wie zu mergen? MULTIPoint auf Point <br/> 
Woher weiß ich, dass ein Unfallspunkt an einer Ampel stattgefunden hat.

https://fbinter.stadt-berlin.de/fb_daten/beschreibung/brw/BRW_Vorblatt_2019.pdf
Helfen Ampeln bei der Reduktion von Abbiege und Kreuzunfällen

In [27]:
bodenrichtwerte = bodenrichtwerte.drop(["GEMEINDE","BEZIRK","VERFAHRENSART","STICHTAG","BEITRAGSZUSTAND","LUMNUM"], axis=1)
bodenrichtwerte.head()

,ANWERT,BRW,NUTZUNG,GFZ,geometry
0,None,500,W - Wohngebiet,0.7,"POLYGON ((378075.888 5825093.591, 378105.795 5..."
1,None,6500,M1 - Kerngebiet,4.5,"POLYGON ((392611.666 5819396.990, 392646.717 5..."
2,None,2500,W - Wohngebiet,0.6,"POLYGON ((387458.479 5819663.963, 387462.024 5..."
3,None,360,W - Wohngebiet,0.4,"POLYGON ((397541.418 5810882.744, 397551.203 5..."
4,None,60,G - Gewerbe,NaN,"MULTIPOLYGON (((394216.175 5833905.236, 394164..."

In [28]:
bodenrichtwerte.describe()

              GFZ
count  855.000000
mean     1.196140
std      1.102752
min      0.100000
25%      0.400000
50%      0.800000
75%      1.600000
max      4.500000

Mergen -> Liegt der Unfallsort im Polygon

Tempolimits

In der Karte sind für das gesamte Berliner Straßennetz die von den jeweils zuständigen Behörden (zentrale Straßenverkehrsbehörde bei der Verkehrslenkung Berlin für das Hauptnetz/StEP-Netz, bezirkliche Straßenverkehrsbehörden für das Nebennetz/nicht StEP-Netz sowie die Straßenbaulastträger) angeordneten Höchstgeschwindigkeiten dargestellt. Hierbei wird Tempo 50 (als gemäß StVO allgemeingültige Höchstgeschwindigkeit in Ortschaften) nicht explizit ausgewiesen, sondern nur die Abweichungen hiervon – lediglich im Autobahnnetz wird auch eine angeordnete Höchstgeschwindigkeit von 50 km/h dargestellt.

Über die Sachdatenabfrage lassen sich, bezogen auf einen Straßenabschnitt, weitere Merkmale zu der jeweils angeordneten zulässigen Höchstgeschwindigkeit ermitteln, z.B. der Grund der Anordnung (wie Schulwegsicherung, Lärmschutz oder dgl.) oder eine Einschränkung der zeitlichen Gültigkeit (z.B. Mo-Fr 6:00-9:00 Uhr).

In der Karte dargestellte Geschwindigkeitsangaben sind auf das sog. Detailnetz Berlin, dem einheitlichen Straßennetz Berlins für verkehrliche Belange, referenziert.

In [29]:
#bodenrichtwerte = bodenrichtwerte.drop(["ELEM_NR","VRICHT_TXT","VERFAHRENSART","STICHTAG","BEITRAGSZUSTAND","LUMNUM"], axis=1)
tempolimits.head()

,ELEM_NR,VRICHT_TXT,WERT_VES,ZEIT_T,TAG_T,DURCH_T,DANN_T,DAT_T,geometry
0,62550035_63550004.02,beide Richtungen,30.0,None,None,angeordnete Verkehrseinschränkung,None,None,"MULTILINESTRING ((407859.700 5820238.792, 4080..."
1,62550029_62550020.02,beide Richtungen,30.0,None,None,angeordnete Verkehrseinschränkung,None,None,"MULTILINESTRING ((407872.095 5820573.080, 4078..."
2,62540035_62550024.02,beide Richtungen,30.0,None,None,angeordnete Verkehrseinschränkung,None,None,"MULTILINESTRING ((407917.759 5819968.557, 4079..."
3,62540035_62540036.02,beide Richtungen,30.0,None,None,angeordnete Verkehrseinschränkung,None,None,"MULTILINESTRING ((407914.056 5819968.285, 4079..."
4,62550001_62550021.01,beide Richtungen,30.0,07:00 - 17:00,Montag bis Freitag,Kinder,Zeitangabe,None,"MULTILINESTRING ((407935.307 5820859.254, 4079..."

In [30]:
from bs4 import BeautifulSoup
import requests
import numpy as np

#scrape data
page = requests.get('http://www.wetter-berlin-online.de/j2018.htm')
soup = BeautifulSoup(page.content, 'lxml')

table = soup.find(text='Datum').find_parent('table')
df_wetter2018 = pd.read_html(str(table))[0]

#drop last 7 rows
df_wetter2018.drop(df_wetter2018.tail(7).index,inplace=True)

#clean data
df_wetter2018 = df_wetter2018.filter(['Datum','ATp. +10m', 'Rel. Feuchte', 'Luftdruck', 'Regen', 'Wind-Geschw.', 'Sonnenschein', 'Helligkeit', 'Solar', 'Taupunkt', 'Windchill'])
df_wetter2018 = df_wetter2018.rename(index=str, columns={"Datum": "date", "ATp. +10m": "Grad"})

df_wetter2018 = df_wetter2018.apply(lambda x: x.str.replace(',','.'))
df_wetter2018['Grad'] = df_wetter2018['Grad'].str.rstrip('°C')
df_wetter2018['Rel. Feuchte'] = df_wetter2018['Rel. Feuchte'].str.rstrip('%')
df_wetter2018['Luftdruck'] = df_wetter2018['Luftdruck'].str.rstrip('hPa')
df_wetter2018['Regen'] = df_wetter2018['Regen'].str.rstrip('l/m²')
df_wetter2018['Wind-Geschw.'] = df_wetter2018['Wind-Geschw.'].str.slice(0, -12)
df_wetter2018['Sonnenschein'] = df_wetter2018['Sonnenschein'].str.rstrip('h')
df_wetter2018['Solar'] = df_wetter2018['Solar'].str.rstrip('W/m²')
df_wetter2018['Taupunkt'] = df_wetter2018['Taupunkt'].str.rstrip('°C')
df_wetter2018['Windchill'] = df_wetter2018['Windchill'].str.rstrip('°C')


for index, row in df_wetter2018.iterrows():
    if ('klux' in row['Helligkeit']):
        row['Helligkeit'] = row['Helligkeit'].rstrip('klux')
        row['Helligkeit'].replace(",", ".")
        value = round(float(row['Helligkeit']) *1000,2)
        row['Helligkeit'] = str(value)
    else:
        row['Helligkeit'] = row['Helligkeit'].rstrip('lux')

row['Helligkeit'] = pd.to_numeric(row['Helligkeit'])


df_wetter2018['date'] = pd.to_datetime(df_wetter2018['date'])

df_wetter2018['date'] = df_wetter2018['date'].dt.strftime('%Y-%m-%d')

In [31]:
df_wetter2018.head()

,date,Grad,Rel. Feuchte,Luftdruck,Regen,Wind-Geschw.,Sonnenschein,Helligkeit,Solar,Taupunkt,Windchill
0,2018-01-01,6.7,70,1000.5,0.4,11.6,0.00,0,0,1.6,5.3
1,2018-02-01,5.4,83,1006.6,5.4,8.2,0.00,0,0,2.7,3.7
2,2018-03-01,5.5,87,986.2,15.5,35.6,0.00,0,0,3.5,0.4
3,2018-04-01,6.7,82,991.7,2.9,16.7,0.00,0,0,3.8,3.6
4,2018-05-01,6.2,75,997.3,2.2,9.3,0.00,0,0,2.1,4.7

In [32]:
len(merge3["OBJECTID"].unique().tolist())

13649

In [68]:
merge3 = merge3.drop(["ULAND","UREGBEZ","UJAHR"], axis=1)
merge3["ANTEIL_PKW"] = merge3["PKW"]*100/merge3["DTV"]
merge3["ANTEIL_PKW"] = merge3["ANTEIL_PKW"].fillna(0)
merge3["ANTEIL_LKW"] = merge3["LKW"]*100/merge3["DTV"]
merge3["ANTEIL_LKW"] = merge3["ANTEIL_LKW"].fillna(0)
merge3["ANTEIL_LIEFERWAGEN"] = merge3["LIEFERWAGEN"]*100/merge3["DTV"]
merge3["ANTEIL_LIEFERWAGEN"] = merge3["ANTEIL_LIEFERWAGEN"].fillna(0)
merge3["ANTEIL_LINIENBUSSE"] = merge3["LINIENBUSSE"]*100/merge3["DTV"]
merge3["ANTEIL_LINIENBUSSE"] = merge3["ANTEIL_LINIENBUSSE"].fillna(0)
merge3.loc[merge3["ANTEIL_LINIENBUSSE"] == np.inf, ['DTV']] = merge3.loc[merge3["ANTEIL_LINIENBUSSE"] == np.inf, ['LINIENBUSSE']]
merge3.loc[merge3["ANTEIL_LINIENBUSSE"] == np.inf, ['ANTEIL_LINIENBUSSE']] = 100
merge3["ANTEIL_REISEBUSSE"] = merge3["REISEBUSSE"]*100/merge3["DTV"]
merge3["ANTEIL_REISEBUSSE"] = merge3["ANTEIL_REISEBUSSE"].fillna(0)
merge3["ANTEIL_KRAD"] = merge3["KRAD"]*100/merge3["DTV"]
merge3["ANTEIL_KRAD"] = merge3["ANTEIL_KRAD"].fillna(0)
merge3 = merge3.drop(["METER","HERKUNFT","PKW","LKW","LIEFERWAGEN","LINIENBUSSE","REISEBUSSE","KRAD"], axis=1)
merge3 = merge3.drop(["GEMEINDE","BEZIRK","VERFAHRENSART","STICHTAG","BEITRAGSZUSTAND","LUMNUM"], axis=1)
# Feld Nahe Ampel erzeugen
merge3['NAHE_AMPEL'] = 0
merge3.loc[~merge3["KNAME"].isna(), ['NAHE_AMPEL']] = 1
merge3 = merge3.drop(["NAME","KNAME","PLR_NAME"], axis=1)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [34]:
merge3.head()

,OBJECTID,UKREIS,UGEMEINDE,UMONAT,USTUNDE,UWOCHENTAG,UKATEGORIE,UART,UTYP1,ULICHTVERH,IstRad,IstPKW,IstFuss,IstKrad,IstGkfz,IstSonstige,STRZUSTAND,LINREFX,LINREFY,DTV,EW2010,VBUS,VBUS_PERS,GESLAERM,GESLAERM_PERS,ANWERT,BRW,NUTZUNG,GFZ,geometry,ANTEIL_PKW,ANTEIL_LKW,ANTEIL_LIEFERWAGEN,ANTEIL_LINIENBUSSE,ANTEIL_REISEBUSSE,ANTEIL_KRAD
0,199408,1,1,4,16,4,3,1,5,0,1,0,0,0,0,1,0,799723.3592,5.827459e+06,17010.0,8107.0,sehr hoch,sehr hoch,sehr hoch,sehr hoch,None,6500,M1 - Kerngebiet,4.5,"MULTIPOLYGON (((799733.359 5827458.739, 799732...",82.704292,3.421517,10.205761,0.411523,0.376249,2.880658
1,201492,1,1,6,18,5,3,1,5,0,1,1,0,0,0,1,0,799718.0909,5.827388e+06,17010.0,8107.0,sehr hoch,sehr hoch,sehr hoch,sehr hoch,None,6500,M1 - Kerngebiet,4.5,"MULTIPOLYGON (((799728.091 5827388.275, 799727...",82.763081,3.421517,10.205761,0.352734,0.376249,2.880658
2,199878,1,1,4,12,5,3,0,2,0,1,1,0,1,0,0,0,799730.1678,5.827540e+06,28800.0,8168.0,hoch,sehr hoch,hoch,hoch,None,6500,M1 - Kerngebiet,4.5,"MULTIPOLYGON (((799740.168 5827539.924, 799739...",82.062500,3.416667,10.201389,0.625000,0.451389,3.243056
3,199728,9,9,4,15,2,3,0,7,0,0,1,0,0,0,1,0,805815.7681,5.819631e+06,8280.0,7678.0,mittel,hoch,mittel,mittel,None,360,W - Wohngebiet,0.4,"MULTIPOLYGON (((805825.768 5819630.742, 805825...",79.734300,3.333333,10.193237,4.468599,0.193237,2.077295
4,205339,9,9,9,9,1,3,6,2,0,0,1,1,0,0,0,0,805817.2609,5.819649e+06,8280.0,7678.0,mittel,hoch,mittel,mittel,None,360,W - Wohngebiet,0.4,"MULTIPOLYGON (((805827.261 5819648.791, 805826...",79.734300,3.333333,10.193237,4.468599,0.193237,2.077295

In [35]:
merge3.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 13649 entries, 0 to 13648
Data columns (total 36 columns):
OBJECTID              13649 non-null int64
UKREIS                13649 non-null int64
UGEMEINDE             13649 non-null int64
UMONAT                13649 non-null int64
USTUNDE               13649 non-null int64
UWOCHENTAG            13649 non-null int64
UKATEGORIE            13649 non-null int64
UART                  13649 non-null int64
UTYP1                 13649 non-null int64
ULICHTVERH            13649 non-null int64
IstRad                13649 non-null int64
IstPKW                13649 non-null int64
IstFuss               13649 non-null int64
IstKrad               13649 non-null int64
IstGkfz               13649 non-null int64
IstSonstige           13649 non-null int64
STRZUSTAND            13649 non-null int64
LINREFX               13649 non-null float64
LINREFY               13649 non-null float64
DTV                   11565 non-null float64
EW2010                13313 non-null float64
VBUS                  13258 non-null object
VBUS_PERS             13258 non-null object
GESLAERM              13258 non-null object
GESLAERM_PERS         13258 non-null object
ANWERT                415 non-null object
BRW                   12581 non-null object
NUTZUNG               12581 non-null object
GFZ                   11114 non-null float64
geometry              13649 non-null geometry
ANTEIL_PKW            11554 non-null float64
ANTEIL_LKW            11554 non-null float64
ANTEIL_LIEFERWAGEN    11554 non-null float64
ANTEIL_LINIENBUSSE    11556 non-null float64
ANTEIL_REISEBUSSE     11554 non-null float64
ANTEIL_KRAD           11554 non-null float64
dtypes: float64(11), geometry(1), int64(17), object(7)
memory usage: 3.7+ MB